### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by rollecode** [silver-leaf/accessible-nav-wp#1]
I love this! Perhaps the most accessible-ready JS nav I have found, yet simple. Any ideas for adding animations for drop downs, desktop or mobile? with display and auto height is kinda impossible to have them just with CSS...

**Comment by silver-leaf** [comment]
Hi there, sorry I didn't see this earlier.

I hadn't really thought about this much further, but I have recently been working on something else that uses this and have made some improvements and will update this (sort of) soon.  Maybe then would be a good time to add those kinds of enhancements?

**Comment by rollecode** [comment]
Actually, I forgot I posted this and implemented the animations myself (at least for desktop). Using your navigation in our starter theme, the changes I've done can be found [here](https://github.com/digitoimistodude/air/blob/master/sass/navigation/_nav-desktop.scss#L17), live [demo](https://dudetest.xyz/air/) can be found here. If it wouldn't be fully SASS, I'd made a pull request...

Not sure what is the best way to add animations on mobile though, because height cannot be animated easily with css-only.

If you have ideas about implementing animations, go ahead, I (and other people) might find them useful :)

**Comment by christianmagill** [comment]
@ronilaukkarinen, it seems this dropdown doesn't detect whether the menu is visible or not. In your demo the items can go off screen.

**Comment by rollecode** [comment]
@christianmagill Hmm funny that you mention after 3 years 😃  The navigation pattern of ours has been improved tremendously since then. We have rewritten lots of parts regarding to the latest accessibility requirements of our clients (and for us as well, for example my wife is hearing and vision impaired and uses keyboard). The currently a bit outdated/incomplete [menu.js](https://github.com/argenteum/accessible-nav-wp/blob/1ac04fa83743c839682969337078d41bf45050d8/menu.js) in this repository is no longer the same than our [navigation.js](https://github.com/digitoimistodude/air-light/blob/6cb8a1fb0f409598e1761ae71a06dae0e2f92e2a/js/src/modules/navigation.js).

However I'm not sure what you mean by "doesn't detect whether the menu is visible or not". In which viewport? With which tool? Mouse, keyboard, something else? Perhaps you are referring to [this issue](https://github.com/digitoimistodude/air-light/issues/5)? Keyboard navigation and everything else should we working 100%.

**Comment by rollecode** [comment]
Also, I have implemented minor animations with padding transitions, so this issue can finally be closed.

**Comment by christianmagill** [comment]
@ronilaukkarinen, yes, that is the issue I speak of.

**Comment by rollecode** [comment]
@christianmagill Yeah. We try to avoid multi-level dropdowns as much as possible and if there is one it shouldn't be the last item. But we're working on that issue, I already have an idea and it will soon be fixed.

I'm proud to say all the other thousands of requirements have already been filled. The dropdown menu even closes down while you press ESC during hovering with _mouse_. I have not seen this functionality in any other navigation.

If you have any thoughts about the development of Air-light navigation, please send them [here](https://github.com/digitoimistodude/air-light/issues).
